### ISSUE TITLE
Operaciones CRUD sobre reuniones

### ISSUE THREAD

**Issue by CarlosSandoval-03** [El-Clan-Del-Bug/UniVerse-Backend#8]
## Descripción de la tarea

Implementar sistema de rutas y controladores de las operaciones básicas CRUD sobre reuniones.

---

## Criterios de aceptación

- [x] Crear ruta que permita al usuario de una comunidad crear una reunión.
- [x] Implementar un método en el controlador de "Meetings", que permita generar un nuevo registro.
- [x] Implementar un método en el controlador de "Meetings", que permita listar los registros.

**Comment by GianK19** [comment]
> ## Descripción de la tarea
> Implementar sistema de rutas y controladores de las operaciones básicas CRUD sobre reuniones.
> 
> ## Criterios de aceptación
> * [x]  Crear ruta que permita al usuario de una comunidad crear una reunión.
> * [x]  Implementar un método en el controlador de "Meetings", que permita generar un nuevo registro.
> * [x]  Implementar un método en el controlador de "Meetings", que permita listar los registros.

Las 3 Sub Issues ya fueron realizadas

**Comment by GianK19** [comment]
Mejor dejo que el líder de Backend haga eso :v
